### ISSUE TITLE
Discounts on memberships getting inappropriately auto-applied on backend

### ISSUE THREAD

**Issue by Stoob** [dlobo/org.civicrm.module.cividiscount#102]
![member-1](https://cloud.githubusercontent.com/assets/1683473/7894222/5258241a-061b-11e5-9628-cd577278f849.png)
![member-2](https://cloud.githubusercontent.com/assets/1683473/7894223/56846daa-061b-11e5-8589-98f7928aa8da.png)

It's my understanding the attached membership discount is NOT supposed to be auto applied.  But when on the "back end" a member is created, the discount is applied without entering a code.  

Interestingly this only happens for a single membership discount.  Other discounts on memberships (which exist) do not show up as auto-applied.

**Comment by lcdservices** [comment]
I'm seeing this as well. It's particularly a problem when renewing a membership. You may use discounts for the initial signup, and then want to renew them at the standard rate. But the listing of membership types applies the discount automatically with no option to apply the standard rate.

**Comment by Stoob** [comment]
The back-office workaround is to manually change the contribution amount in the section below the membership.  But this is not a reliable long-term solution and I'd love to contribute to a patch to fix this issue.

**Comment by monishdeb** [comment]
@Stoob I was unable to replicate on 4.6 against latest 3.1 CiviDiscount. (Also you van check on 4.6 demo site http://d46.demo.civicrm.org) Here are my steps to replicate with screenshots -

1) Created Discount Rule with selected MT(Memebership Type(s)) http://snag.gy/jBcUP.jpg
2) On New Membership page the code wasn't auto applied to membership http://snag.gy/EpImK.jpg 
3) Only on applying Discount code the MT got discounted http://snag.gy/zbPsV.jpg

Am I missing something ?

**Comment by lcdservices** [comment]
I actually just implemented and tested the latest version (which was released a couple days ago) and it seems to have fixed the issue. Stoob, you should test and confirm that it fixed it for you as well.

**Comment by Stoob** [comment]
This bug affected 3.0, version 3.1 appears to have fixed the issue.  Thanks.  Closed.
