### ISSUE TITLE
API (CiviDiscount, get) does not exist (join the API team and implement it!)

### ISSUE THREAD

**Issue by magnolia61** [dlobo/org.civicrm.module.cividiscount#103]
running the current master as well as the released 3. version gets me the following message when I want to save a discount rule, leaving the api field empty.

Sorry but we are not able to provide this at the moment.
API (CiviDiscount, get) does not exist (join the API team and implement it!)

Am I missing something?

**Comment by colemanw** [comment]
I believe the api name is "Discount" not "CiviDiscount". Did you find that name in the documentation or api explorer or... ?

**Comment by magnolia61** [comment]
it is displayed as an error message when saving a new discount rule...
Op 1 jun. 2015 19:51 schreef "colemanw" <notifications@github.com>:

**Comment by monishdeb** [comment]
@magnolia61 the api name is "DiscountCode", you will find the same under api explorer's entity drop down. (screenshot http://snag.gy/YGkC6.jpg) 

Another simple way to know the apiname is simply to look on the filename under 
<extension-directory>/api/v3/<api-name>.php

**Comment by magnolia61** [comment]
Maybe it is good to know that I am not in any way coding anything. Just using CiviDiscount out of the box and trying to save a new discount rule through the gui...

**Comment by monishdeb** [comment]
Ya even I tried to find the occurrence of that API error from UI while creating a Discount Rule, also grepped its usage in the extension itself but didn't find any. :( In my opinion documentation should be done on what are the api options available in CiviDiscount for future reference

**Comment by colemanw** [comment]
Try upgrading to the new release of CiviDiscount.

**Comment by eileenmcnaughton** [comment]
I think this should be closed - per Monish's comment - the api does work
