### ISSUE TITLE
Trim whitespace around code when entered

### ISSUE THREAD

**Issue by eileenmcnaughton** [dlobo/org.civicrm.module.cividiscount#109]
When trying to compare different versions of this extension I find that at some point the discountcode was being trimmed - this seems to be a sensible thing which should be re-introduced

diff --git a/cividiscount.php b/cividiscount.php
index 93a7f47..b75ad55 100644
--- a/cividiscount.php
+++ b/cividiscount.php
@@ -137,7 +137,7 @@ function cividiscount_civicrm_buildForm($fname, &$form) {

     if ($form->getVar('_single') == 1 || in_array($form->getVar('_context'), array('membership', 'standalone'))) {
       _cividiscount_add_discount_textfield($form);
-      $code = CRM_Utils_Request::retrieve('discountcode', 'String', $form, false, null, 'REQUEST');
+      $code = trim(CRM_Utils_Request::retrieve('discountcode', 'String', $form, false, null, 'REQUEST'));
       if ($code) {
         $defaults = array('discountcode' => $code);
         $form->setDefaults($defaults);

**Comment by colemanw** [comment]
FYI In github "issues" and "pull-requests" are pretty much the same thing. If you open a PR there's no need to open an issue as well.
