### ISSUE TITLE
Auto Member status discount isn't saved

### ISSUE THREAD

**Issue by fmboisclair** [dlobo/org.civicrm.module.cividiscount#116]
When I define an auto discount based upon membership status of 'New' (also try do the same with some other status), save and reedit, the membership statuses disappear. Working with CiviCRM 4.6.4 and CiviDiscount 3.1.  I also recreate the problem with the demo site.

**Comment by monishdeb** [comment]
Submitted the PR https://github.com/dlobo/org.civicrm.module.cividiscount/pull/119
