### ISSUE TITLE
Multiple CiviContribute Errors Under WordPress

### ISSUE THREAD

**Issue by erogers** [dlobo/org.civicrm.module.cividiscount#118]
CiviDiscount is generating multiple errors on CiviContribute pages running on WordPress, when a user is logged in.

Warning: array_keys() expects parameter 1 to be array, null given in /home/..../www/www/wp-content/plugins/files/civicrm/extensions/org.civicrm.module.cividiscount/CRM/CiviDiscount/DiscountCalculator.php on line 108

Warning: Invalid argument supplied for foreach() in /home/..../www/www/wp-content/plugins/files/civicrm/extensions/org.civicrm.module.cividiscount/CRM/CiviDiscount/DiscountCalculator.php on line 108

This error repeats 27 times for me

**Comment by monishdeb** [comment]
Already fixed https://github.com/dlobo/org.civicrm.module.cividiscount/pull/107
