### ISSUE TITLE
change "Member Discount" to "Includes member discount of:"

### ISSUE THREAD

**Issue by Stoob** [dlobo/org.civicrm.module.cividiscount#122]
In cases where an event includes both early bird pricing AND a member discount, I've gotten feedback from more than one client that the attached is confusing.   The 'full price' without early bird or membership is $100.

This is what I hear: Is the member discount $25 off or is it $25?  Does my membership discount stack with the early bird pricing or not?  Why is the internet so hard and where is my coffee?

We can't fix ______, but changing the wording would help make sense of the discounts a great deal.  Word Replacements is no effect.

![uhhh](https://cloud.githubusercontent.com/assets/1683473/10007412/dc3cda14-6079-11e5-8d0f-83a564abd33a.png)

**Comment by monishdeb** [comment]
Tested and merged related PR https://github.com/dlobo/org.civicrm.module.cividiscount/pull/123
