### ISSUE TITLE
Suddenly Stopped Working

### ISSUE THREAD

**Issue by osarusan82** [dlobo/org.civicrm.module.cividiscount#134]
I was using CiviDiscount for about a month with no problems, but all of a sudden, none of the discounts apply anymore.

No matter what is put in the discount box, the following error appears:

Please correct the following errors in the form fields below:
The discount code you entered is invalid.

Even with discounts that have worked in the past (and have not expired or changed) they suddenly do not work any more. What could have happened to make the coupons no longer work at all??

**Comment by veda-consulting** [comment]
Which version are you running? Did you run an upgrade?

**Comment by osarusan82** [comment]
I'm using CiviDiscount 3.1 and CiviCRM 4.6.10.
This is the first install of CiviDiscount that I have put in, and I did not upgrade it.
I also have not upgraded CiviCRM since installing CiviDiscount.
I didn't make any changes between the time it was working and the time it stopped working.

**Comment by osarusan82** [comment]
I somehow fixed it by deleting the plugin files and re-uploading them. It works now. Not sure why or how it got messed up, but I'm glad to say it is working again.

**Comment by veda-consulting** [comment]
Thats great - I'll close the issue



Veda Consulting
t : +44 (0) 20 3239 1156
m : +44 (0) 77 4216 3491
e : parvez@vedaconsulting.co.uk
w : www.vedaconsulting.co.uk

**Comment by veda-consulting** [comment]
@colemanw I think we can close this issue?
