### ISSUE TITLE
possible variable typo?

### ISSUE THREAD

**Issue by elkram** [dlobo/org.civicrm.module.cividiscount#137]
I could be very wrong, but I think I see a typo in a variable reference.
Whilst reviewing a diff between 3.0 and 3.1 releases.

in: /CRM/CiviDiscount/DAO/Item.php

on lines: 366 & 390
`self::$_import['ount_item'] = &$fields[$name];`

shouldn't this be:
`self::$_import['cividiscount_item'] = &$fields[$name];`

I looked for 'ount_item', and only found 'cividiscount_item'

**Comment by elkram** [comment]
Similar possible typo?

in: /CRM/CiviDiscount/DAO/Track.php

on lines: 245 & 269
`self::$_import['ount_track'] = &$fields[$name];`
`self::$_export['ount_track'] = &$fields[$name];`

looking for 'out_track' and I'm only finding 'cividiscount_track'

*Hoping someone who is more familiar with the code base can confirm these.*

**Comment by elkram** [comment]
Here's a patch, presuming this issue is not erroneous.
[org.civicrm.module.cividiscount-3.1--137-1.patch.txt](https://github.com/dlobo/org.civicrm.module.cividiscount/files/104149/org.civicrm.module.cividiscount-3.1--137-1.patch.txt)

**Comment by colemanw** [comment]
Thanks for the patch @elkram - could you please open a pull-request for that?

**Comment by elkram** [comment]
Pardon my etiquette/process fail.  Head in code for decades, but relatively new to repos.
I've confirmed the same code is present in the Master branch.  I'll go RTFM, regarding pull requests.

**Comment by elkram** [comment]
Okay:
I've pulled the Master down
Made a branch: issue-137
Made the edits, diff check, etc.
Prepared the commit, but cannot push it.  (no access.)

Is there another method?  (I missed a step?)

**Comment by colemanw** [comment]
Nice :+1:
