### ISSUE TITLE
getValidDiscounts SELECT SQL doesn't include expire_on and active_on in the WHERE clause

### ISSUE THREAD

**Issue by elkram** [dlobo/org.civicrm.module.cividiscount#138]
Hopefully someone more familiar with the code can confirm.

In getValidDiscounts, the SQL WHERE clause, only looks at the manual check box 'is_active' and the 'count_use'.  The activation and expiration are handled elsewhere for some reason.

release: 3.1
in: /CRM/CiviDiscount/BAO/Item.php

@ line: 168
`WHERE is_active = 1`
`AND (count_max = 0 OR count_max > count_use)`

should probably be:
`WHERE is_active = 1`
`AND active_on <= NOW()`
`AND expire_on > NOW()`
`AND (count_max = 0 OR count_max > count_use)`

**Comment by elkram** [comment]
I can see this might be handled here: isValid()

Why not in SQL?  Seems odd.  I can find only one call to isValid.

Is there a reason we create "getValidDiscounts" with expired or not yet active items?
If not, I propose moving those tests to the SQL statement.

**Comment by elkram** [comment]
this patch adds the conditions:  (might consider revisiting the isValid() function to remove redundant tests, presuming this issue is not erroneous.)
[org.civicrm.module.cividiscount-3.1--138-1.patch.txt](https://github.com/dlobo/org.civicrm.module.cividiscount/files/104161/org.civicrm.module.cividiscount-3.1--138-1.patch.txt)

**Comment by elkram** [comment]
As far as I can tell the only call to isValid, is during getValidDiscounts.
That makes the tests in IsValid redundant to SQL WHERE clauses that perform the same tests.
Adding the above SQL will negate the need for the following static functions:
isExpired
isActive
isEnabled (test already in SQL)
isValid (which points to the 3 above, and includes a test that already exists in SQL.)

**Comment by colemanw** [comment]
There is definitely some cruft in this code - it was written years ago and has been ported several times. Please feel free to open a PR with your cleanups.

**Comment by elkram** [comment]
I'll give the code changes several tests on my 3.1 dev copy of our live site.  Shouldn't take long.  The gist seems to have remained the same for getValidDiscounts from 3.0 through to current master.

**Comment by elkram** [comment]
I've confirmed master is identical to 3.1 for /CRM/CiviDiscount/BAO/Item.php
I've completed tests to and corrected my SQL proposal; getValidDiscounts is behaving.
creating PR… posted shortly.
