### ISSUE TITLE
Untranslated strings in cividiscount

### ISSUE THREAD

**Issue by eileenmcnaughton** [dlobo/org.civicrm.module.cividiscount#144]
Basically at some point this needs re-doing but the way Coleman said it should be 

https://github.com/dlobo/org.civicrm.module.cividiscount/pull/143#event-550059781

**Comment by colemanw** [comment]
Fixed with https://github.com/dlobo/org.civicrm.module.cividiscount/commit/b44caaf975b12b7f3926a58c83b3dea467134efd
