### ISSUE TITLE
remove question mark in url

### ISSUE THREAD

**Issue by sunilpawar** [dlobo/org.civicrm.module.cividiscount#151]
under 
function cividiscount_civicrm_navigationMenu
https://github.com/dlobo/org.civicrm.module.cividiscount/blob/master/cividiscount.php#L1148
remove "?" mark in the url, it break for unclean url
'url'        => 'civicrm/cividiscount?reset=1',
**TO** 
'url'        => 'civicrm/cividiscount',

**Comment by kurund** [comment]
@sunilpawar Can you please submit a PR for the same.
