### ISSUE TITLE
Performance issues with many discounts

### ISSUE THREAD

**Issue by twomice** [dlobo/org.civicrm.module.cividiscount#154]
I have a site here with over 150 active discount codes, all based on either event ID or event type, none of which are set for Automatic Discounts.

When loading any event registration page, the page takes around 30 seconds to load. Xdebug profiling output shows that this delay is caused by CRM_CiviDiscount_DiscountCalculator::checkDiscountsByEntity(), which performs a 'get event' API call on every one of those discount codes, in order to check whether any events meet the requirements of the discount code.

It seems unnecessary to check non-autodiscount codes when loading the event registration page; rather, if we wait until someone submits a code, we can simply check whether that code applies to the given event.

Would a PR taking such an approach be useful, or should I consider a different solution pathway?

**Comment by twomice** [comment]
Answering part of my own question:
CiviDiscount has to know if the event has an active discount code, so that it can display or hide the Discount Code field.

So at this point I'm thinking that the data structure is the real problem here: currently, the storage mechanism associating a discount code with one or more events, or one or more event types, etc., is a single column delimited with CRM_Core_DAO::VALUE_SEPARATOR.  This makes it hard to run a single query that can tell what discounts are associated with any given event, which is why the code is running one 'get event' API call for every discount code.

Is it worth discussing changes to that schema for the sake of avoiding long page loads with large numbers of discount codes?

**Comment by Stoob** [comment]
I see all the event ID sandwiched in a single column, are they separated by an invisible character?  Could we re-write a creative query rather than re-build the schema?   Could the query be from the perspective of the event with a "= xxxx OR LIKE = '%xxxx~%' in the WHERE clause where ~ is the invisible character?  Simply to see if it's number is written anywhere in that column, in any row, and then display the box.

**Comment by twomice** [comment]
I've cross-posted this on JIRA: https://issues.civicrm.org/jira/browse/CRM-18562  What's the best place to post issues for this extension?

**Comment by twomice** [comment]
Tim from the core team points out that issues are best addressed on JIRA. Closing this in favor of https://issues.civicrm.org/jira/browse/CRM-18562
