### ISSUE TITLE
Standardize cividiscount button field to match rest of Civi form elements

### ISSUE THREAD

**Issue by herbdool** [dlobo/org.civicrm.module.cividiscount#178]
The rest of the Civi form elements use divs and have particular classes on the elements. This field should be standardized with that *and* stop using tables. This makes for poor ability to work on mobile devices.

**Comment by herbdool** [comment]
@colemanw love it when a PR gets merged within hours! Thanks

Do you need to cut a new release? I'm patching the extension in the meanwhile

**Comment by colemanw** [comment]
@Herb do you feel like spreading the love and reviewing any of the other 
open PRs for this extension before we do a release?

**Comment by herbdool** [comment]
@colemanw I can try take a look over the next week or so.
