### ISSUE TITLE
Event Discount applied to whole priceset instead of selected fields

### ISSUE THREAD

**Issue by randomseb** [dlobo/org.civicrm.module.cividiscount#35]
When applying discount to price set for Event, the entire priceset is being discounted, instead of the selected fields

CiviCRM 4.4.3
CiviDiscount 2.5

**Comment by shawnholt** [comment]
I have the reverse problem with Civicrm 4.5.5 / CiviDiscount 3.0.  
I enabled for an event and didn't specify a price set field.  The discount code would not apply to the total (nor does it give an error). 

 If I specify the price set field it does apply to the price set field and to the total.

Should the price set field be required?  I assumed that omitting it would apply to the total amount.
