### ISSUE TITLE
Extend Event discount inclusion options

### ISSUE THREAD

**Issue by eileenmcnaughton** [dlobo/org.civicrm.module.cividiscount#39]
We have been looking at cividiscount for a customer who would like to be able to apply discounts to events without having to go back & configure every event they add with a discount. 

My expectation was that if you configured a price set in the section "If you use price sets for your events, you also need to select any discountable price sets below." and did not select any event then that would mean that the discount would be applied to 'ALL events that have that price set item configured'. This doesn't appear to happen - is it a bug I can patch or is it a feature? 

If the latter I guess I could potentially add an 'apply to all events' checkbox - or a select box for events types (we may do this as well any way).  I think the event select select would need to grey out if an event type is selected - & vice versa

**Comment by zorgalina** [comment]
Eileen (someone) - I tried to git clone from eileenmcnaughton/org.civicrm.module.cividiscount to get that branch, but git failed . I'd really like to get this patch/branch if possible. I hope you can point me in the right direction. 
Thank you!

**Comment by zorgalina** [comment]
Sorry, I read the ADVANCED FILTERS Readme at (https://github.com/dlobo/org.civicrm.module.cividiscount) and got the right url for this feature, never mind that last post, Thank you!

**Comment by eileenmcnaughton** [comment]
Closing - this is in 3.0 (& my repo per previous comments for 4.4 - but people on 4.6 should be using main branch)
