### ISSUE TITLE
Using Pricesets for memberships causes Discount Tracking to fail.

### ISSUE THREAD

**Issue by generalredneck** [dlobo/org.civicrm.module.cividiscount#74]
The following is not using any Priceset, but instead what you would find on the Contribution page Membership Section.
![No Pricest](http://www.webpagescreenshot.info/i3/53d92a2f732d72-26483103)

This is using a priceset:
![Priceset](http://www.webpagescreenshot.info/i3/53d92b524e06a0-37510783)

Notice that in this one, $membership_type is an array. This is because you can select more than one. With that said, how is usage going to be tracked on multiple memberships? Should it be per membership or per invoice. In this case I still only have 1 membership but could easily have 2 or 3. For now I'm going to create A PR that fixes it where if you have any of the memberships, it creates only one record.

This is an issue in 2.5 as well as master. See https://github.com/dlobo/org.civicrm.module.cividiscount/blob/master/cividiscount.php#L624

**Comment by eileenmcnaughton** [comment]
Do you mean the discount tracking is failing? Or that the discount is not being offered? I'm not seeing discounts offered on 4.6 for price set memberships
