### ISSUE TITLE
Event reg. fails if number of participants is greater than available usage for unentered manual code

### ISSUE THREAD

**Issue by ATDale** [dlobo/org.civicrm.module.cividiscount#87]
Weird situation: We have a [conference registration] (https://www.eswusa.org/civicrm/event/register?reset=1&id=6) page up, and have both automatic member discounts (unlimited usage), and some manually entered ones (limited to 20-30 uses). One of our members went to register 3 people at once, using only the auto-discount, and got an error saying there weren't enough uses of that code available. One of the manual codes was at 20/21 uses. 

A little testing:
Setting the manual code to 25 uses makes 3 person registration work fine.
Setting the manual code to 20 uses makes 3 person registration work fine.
Setting the manual code to 25 uses and attempting a 7 person registration fails.

My non-code analysis is that the module seems to be checking all possible discount codes versus the number of participants (P), and failing if the available codes is above zero but less than P. Seems like it shouldn't check any codes that aren't entered, but perhaps there's a use case that I'm missing?

**Comment by monishdeb** [comment]
This is been fixed in https://github.com/dlobo/org.civicrm.module.cividiscount/pull/100
