### ISSUE TITLE
Offline registration ("Register Event Participant") missing data for Track table

### ISSUE THREAD

**Issue by zorgalina** [dlobo/org.civicrm.module.cividiscount#89]
When registering a participant for an event, tracking data for entity_id, entity_table and contact_id were skipped.
Adding following lines (line # 647-649 in cividiscount.php) fixes the problem:
      $trackingItem['entity_id'] = $entity_id;
      $trackingItem['entity_table'] = $entity_table;
      $trackingItem['contact_id'] = $contact_id;

I can submit a patch if someone lets me know where I should submit it (a .diff file of cividiscount.php)

**Comment by kurund** [comment]
@zorgalina thanks for the fix. You can fork this repository and submit the PR against master branch

**Comment by zorgalina** [comment]
I forked on eileen mcnaughton's branch, using 'Advanced Filter', as that is
where I found the bug, hope I did it correctly, (I updated/edited the code
in the fork under my name zorgalina).
Thx

On Tue, Apr 7, 2015 at 11:35 PM, Kurund Jalmi <notifications@github.com>
wrote:

> @zorgalina <https://github.com/zorgalina> thanks for the fix. You can
> fork this repository and submit the PR against master branch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dlobo/org.civicrm.module.cividiscount/issues/89#issuecomment-90820213>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by colemanw** [comment]
Can you please create a pull request with your changes?

**Comment by zorgalina** [comment]
Okay - is there a doc/ how- to on this that I should have read?
:((sorry, I just proceeded ' seat of pants' style)
Sent from my HTC One™ X, an AT&T 4G LTE smartphone

----- Reply message -----

**Comment by colemanw** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by zorgalina** [comment]
Thx, Coleman (named after the lantern or stove? ;)

On Wed, Apr 8, 2015 at 1:53 PM, colemanw <notifications@github.com> wrote:

> https://help.github.com/articles/creating-a-pull-request/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dlobo/org.civicrm.module.cividiscount/issues/89#issuecomment-91033975>
> .
>



-- 
زورگلنه ءء لسلی

**Comment by eileenmcnaughton** [comment]
You should re-test this on master. I fixed for membership - but not sure if event got the fix as well or not
