### ISSUE TITLE
CiviDiscount broken in CiviCRM 4.6

### ISSUE THREAD

**Issue by erogers** [dlobo/org.civicrm.module.cividiscount#90]
Running CiviCRM 4.6, CiviDiscount 3.0, and WordPress 4.1

All of my contribution pages showing this error message:

"Warning: array_keys() expects parameter 1 to be array, null given in /home/.../www/wp-content/plugins/files/civicrm/extensions/org.civicrm.module.cividiscount/CRM/CiviDiscount/DiscountCalculator.php on line 114"

**Comment by monishdeb** [comment]
Submitted PR https://github.com/dlobo/org.civicrm.module.cividiscount/pull/107

**Comment by eileenmcnaughton** [comment]
I think this should be closed now - works on 4.6.4 for me & I see there was a fix applied
