### ISSUE TITLE
Could not find valid value for id when applying code to event with price set

### ISSUE THREAD

**Issue by Stoob** [dlobo/org.civicrm.module.cividiscount#92]
The documentation seems to infer that without specific price sets specified, a discount will be applied to ALL price fields, but instead it returns an error.  (see attached and backtrace below)

![price_set_1](https://cloud.githubusercontent.com/assets/1683473/7360958/3caf6430-ed06-11e4-9ed7-42c0425cc5d7.png)
![price_set_2](https://cloud.githubusercontent.com/assets/1683473/7360957/3c496716-ed06-11e4-8fe9-366b8e6688b9.png)

backTrace

#0 /home/resolutions/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(380): CRM_Core_Error::backtrace()
#1 /home/resolutions/www/www/wp-content/plugins/civicrm/civicrm/CRM/Utils/Request.php(105): CRM_Core_Error::fatal("Could not find valid value for id")
#2 /home/resolutions/www/www/wp-content/plugins/civicrm/civicrm/CRM/Event/StateMachine/Registration.php(53): CRM_Utils_Request::retrieve("id", "Positive", Object(CRM_Event_Controller_Registration), TRUE)
#3 /home/resolutions/www/www/wp-content/plugins/civicrm/civicrm/CRM/Event/Controller/Registration.php(43): CRM_Event_StateMachine_Registration->__construct(Object(CRM_Event_Controller_Registration), TRUE)
#4 /home/resolutions/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(330): CRM_Event_Controller_Registration->__construct("Event Registration", TRUE, "null", NULL, "false")
#5 /home/resolutions/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(79): CRM_Core_Invoke::runItem((Array:15))
#6 /home/resolutions/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#7 /home/resolutions/www/www/wp-content/plugins/civicrm/civicrm.php(525): CRM_Core_Invoke::invoke((Array:3))
#8 [internal function](): CiviCRM_For_WordPress->invoke("<div class=\"shortcode1-2\">\n<h1 style=\"text-align: left;\"><span style=\"c...")
#9 /home/resolutions/www/www/wp-includes/plugin.php(213): call_user_func_array((Array:2), (Array:1))
#10 /home/resolutions/www/www/wp-content/themes/greenearth-v1-07/page.php(27): apply_filters("the_content", "[column col=\"1/2\"]\r\n<h1 style=\"text-align: left;\"><span style=\"color: ...")
#11 /home/resolutions/www/www/wp-includes/template-loader.php(74): include("/home/resolutions/www/www/wp-content/themes/greenearth-v1-07/page.php")
#12 /home/resolutions/www/www/wp-blog-header.php(16): require_once("/home/resolutions/www/www/wp-includes/template-loader.php")
#13 /home/resolutions/www/www/index.php(17): require("/home/resolutions/www/www/wp-blog-header.php")
#14 {main}

Sorry but we are not able to provide this at the moment.
Could not find valid value for id

Return to home page.

**Comment by Kajakaran** [comment]
Hi @Stoob 

I have tested it looks like no problem with cividiscount. Could you please check the url format that you are using in the second image. I think civi expects in the format of 'civicrm/event/register&reset=1&id=4'.

Thanks
Kajan

**Comment by Stoob** [comment]
That is the problem exactly, an event discount with no price sets 
applies removes the id= from the URL and causes an error on WordPress.

**Comment by Kajakaran** [comment]
Hi @Stoob ,

I could not reproduce this issue. can we have a session on this?

Thanks
Kajan

**Comment by Stoob** [comment]
There are two issues:  1) the behavior of the no price set selection code is not as described by the extension.  Selecting ZERO price sets should still work   2) the error

I can no longer produce error...issue #2 

However issue #1 still exists.  Please see attached image for a discount code example.  You can use this discount code here:

http://resolutionsnorthwest.org/?page=CiviCRM&q=civicrm/event/register&reset=1&id=132

See that it #1 does not work  and #2 removes the id= of the page from the URL
![price-set](https://cloud.githubusercontent.com/assets/1683473/7660793/283af3b6-fb02-11e4-8a86-f09e75c546f5.png)

**Comment by Kajakaran** [comment]
Hi @Stoob,

a) Issue 1 has been fixed in the following PR. 

https://github.com/dlobo/org.civicrm.module.cividiscount/pull/101

b) issue 2 please find the screenshots

![screenshot_1](https://cloud.githubusercontent.com/assets/7429798/7745677/0631e0de-ffa5-11e4-8f9f-3b1f84699cf4.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/7429798/7745679/06336a9e-ffa5-11e4-8249-0f0de552e9c1.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/7429798/7745678/06331e4a-ffa5-11e4-99c2-bad7baab706f.png)

image 1: discount code configuration screen with price set option not set for the event 'fall fundraiser dinner'

image 2: event registration page for that event before discount applied. look at the URL format

image 3: event registration page after discount applied. look at the URL format.

In your case, image 3 URL goes to somewhere else(with page_id). I think this is happening because of other modules your might have installed in your system, not because of cividiscount.

Thanks

**Comment by Stoob** [comment]
thanks!
