### ISSUE TITLE
Version 2.6 membership discounts don't carry to confirmation screen

### ISSUE THREAD

**Issue by Stoob** [dlobo/org.civicrm.module.cividiscount#93]
![Uploading applied.png…]()
1. enter a code for a membership discount on page one of a contribution page
2. the discount doesn't "carry forward" to the confirmation page (page 2)

In the attached screenshot $110 is NOT the discounted price, it is the full price.  The adjusted price should be 82.50

**Comment by Stoob** [comment]
![applied](https://cloud.githubusercontent.com/assets/1683473/7382781/0e1538ac-edc9-11e4-88a0-05f51aab3243.png)

**Comment by petednz** [comment]
parvez said in an email that this has been fixed

**Comment by Stoob** [comment]
In which version?  Will there be a new release (2.7?) or should I test 
it with trunk?

**Comment by monishdeb** [comment]
This have been fixed in latest 3.1. Tested in 4.6 demo and on local
![rsz_1discount](https://cloud.githubusercontent.com/assets/3735621/9580294/3abd0db2-5016-11e5-896a-ef98eda53613.png)
