### ISSUE TITLE
3.0 not working for automatic event discounts based on membership

### ISSUE THREAD

**Issue by sdragnev** [dlobo/org.civicrm.module.cividiscount#94]
I don't think cividiscount.php:403 can ever evaluate to true if the user is not using a code, the event has no price sets and there's an automatic discount based on a membership.

Here's the line in question:
```
if (!empty($applyToAllLineItems) || CRM_Utils_Array::value($option['id'], $priceFields)) {
```

**Comment by monishdeb** [comment]
PR merged https://github.com/dlobo/org.civicrm.module.cividiscount/pull/120
