### ISSUE TITLE
Discount not calculated correctly in some cases

### ISSUE THREAD

**Issue by sdragnev** [dlobo/org.civicrm.module.cividiscount#99]
If the original price is a float, the discount is not calculated correctly.
cividiscount.php:392 casts the original price as an integer:

```
$originalAmount = (integer) $originalAmounts[$fee_id]['options'][$option_id]['amount'];
```
Not sure why.

**Comment by monishdeb** [comment]
Submitted PR https://github.com/dlobo/org.civicrm.module.cividiscount/pull/107

**Comment by eileenmcnaughton** [comment]
This appears to be merged & can be closed?
